### ISSUE TITLE
[Feature Request] lan support

### ISSUE THREAD

**Issue by spicemint** [conceptualspace/enhance-o-tron-for-plex#1]
hi there, not using app.plex.tv or localhost to access plex, is it possible to include/support local lan nets for usage?

**Comment by conceptualspace** [comment]
There will be soon -- I'm working on a version that has a button in the toolbar that you can click to ask for permissions to access the current site. This would theoretically let users run it on custom URLs.

In the meantime, you could download the source and make a small change yourself which would do the trick:

Edit the manifest.json file and add your Plex IP or hostname to the _permissions_ and _matches_ keys, then zip up the src folder and load it up as a local extension: https://developer.chrome.com/extensions/getstarted

Alternatively let me know the hostname you use and I'd be happy to fire you a custom build :)

**Comment by spicemint** [comment]
that was pretty easy and works, thanks :)
