### ISSUE TITLE
21:9 on secondary ultrawide monitor skews the aspect ratio

### ISSUE THREAD

**Issue by ishai1856** [conceptualspace/enhance-o-tron-for-plex#12]
My primary monitor is a samsung 4k. My secondary is an LG ultrawide. When I try to use the 21:9 zoom on the secondary monitor, the picture uses a stretch zoom and the aspect ratio skews. Is there a fix or a workaround for this? Maybe its the NVIDIA driver or Chrome?
AWESOME product, thanks very much for this. The compressor is just fantastic and the 21:9 zoom is great when it works. 
Please see attached from the latest season of Mando - the y axis doesn't zoom, only the X. 
This is the original video
<img width="1280" alt="original" src="https://github.com/conceptualspace/enhance-o-tron-for-plex/assets/69421676/961e712a-b357-4553-99e5-c8445be99296">
This is with the 21:9 ultrawide zoom enabled
<img width="1280" alt="skew" src="https://github.com/conceptualspace/enhance-o-tron-for-plex/assets/69421676/57047ee3-6ac4-4a8f-8fff-8975e164bf80">
This only occurs with the video fullscreened. In a window it works perfectly.

**Comment by ThatGuyFlytrap** [comment]
Same issue. It works when windowed, but when you use full-screen, it does as shown.

**Comment by ishai1856** [comment]
Issue appears to have resolved itself. No explanation.
