### ISSUE TITLE
Shuffle button no longer showing for libraries

### ISSUE THREAD

**Issue by silembir** [conceptualspace/enhance-o-tron-for-plex#4]
Hello,

I previously loved this extension, especially the Shuffle button for libraries.  Recently, I'm not sure what changed but the Shuffle button is no longer appearing.  I have enabled Enhance-o-tron for my Plex domain and the Play Trailer button is showing for movies so I know that some features of the extension are working.  Any help would be appreciated.  Thanks!

![image](https://i.imgur.com/wJJf988.png)

**Comment by conceptualspace** [comment]
thanks for the report -- confirmed

looks like a breaking change in the latest version of plex web. a fix is forthcoming :)

**Comment by conceptualspace** [comment]
fixed in v1.4.4

**Comment by silembir** [comment]
Thanks for the quick fix!  ♥
