### ISSUE TITLE
Not fucntioning on optional allowed domain

### ISSUE THREAD

**Issue by Cr4zyy** [conceptualspace/enhance-o-tron-for-plex#6]
Using Firefox 99.0 and v 1.5.5 of Enhance-o-tron

On a local domain name (http://box:32400/) or ip also doesnt work, this is how it looks
![image](https://user-images.githubusercontent.com/9981275/162334132-7b427d38-ac56-4bf3-b70f-94f665494ff6.png)

But on app.plex.tv it works fine
![image](https://user-images.githubusercontent.com/9981275/162334287-bfdc9b52-f8e5-4f9b-9868-df456b2f927a.png)

It's not just the player, trailer links etc also arent added.

**Comment by conceptualspace** [comment]
thanks for the report. i'll see if i can replicate on my local system, stand by..

**Comment by conceptualspace** [comment]
hmm so far it seems ok for me. can you check what version of plex web is running? (click the wrench at the top right and then 'general' on the left

![Screenshot from 2022-04-08 13-14-21](https://user-images.githubusercontent.com/4175632/162490249-6e7bd037-6ae7-4881-9f80-17242035a781.png)

**Comment by Cr4zyy** [comment]
Im running 4.76.1 on the latest Plex Media Server build (Version 1.25.9.5721)
![image](https://user-images.githubusercontent.com/9981275/162492457-fe1a3074-1131-49a6-af90-f2bf0709a6b1.png)

app.plex.tv is running Version 4.78.4 so that could be why?


ok I wrote everything above about 10mins ago and started going through other extentions making sure they werent causing issues, when I stumbled across this checkbox on the permissions tab for the extention.
![image](https://user-images.githubusercontent.com/9981275/162495903-ce439278-09f3-4ab2-9740-5349c81fb664.png)

Enabling this fixes the problem instantly, regardless of me enabling it for the domain or not, that toggle solves my issue it seems like.

**Comment by conceptualspace** [comment]
aha! thank you! that seems to be an extra quirk on firefox; in chrome you only need to enable the optional permissions from the toolbar button. it's a bit awkward because what is the point of "optional permissions" if we need to grant explicit permission to all domains. anyway i'll document this on the ff page for other users. glad you figured it out, thanks again
