### ISSUE TITLE
Features do not show up

### ISSUE THREAD

**Issue by Xyven1** [conceptualspace/enhance-o-tron-for-plex#7]
None of the features are showing up (for me) anymore. Tried reinstalling the extension, which didn't work, and I made sure the extension was enabled for the domain (I'm just using app.plex.tv). Potentially an issue with the latest version of Plex.

I did some quick debugging and this is what I've found:
- if I directly copy the source code for a simple feature (like createZoomElem), paste it in the console, and run it, the button shows up and functions normally
- this button will disappear if I minimize or expand the player
- I am not getting any output to the console which seems to be related to enhanceotron

No clue if this is an issue specific to my setup, or if it is due to changes in Plex Web.

**Comment by conceptualspace** [comment]
hmm, i have not heard of this behavior before. can you confirm your OS, browser, and version of plex web?

**Comment by conceptualspace** [comment]
and do you have any other plex extensions? i wonder if something is conflicting

**Comment by Xyven1** [comment]
I am on chrome, windows 11, and version 4.79.4 of plex web. I am not using any other extensions for plex (I also disabled my adblocker to make sure that wasn't affecting it, to no avail).

**Comment by Xyven1** [comment]
This problem seems to have alleviated itself, so I'll close this issue.
